Exercise 1: Introduction to Data Analysis (Easy):
Data analysis - process of collecting, organizing, cleaning, and interpreting data in order to extract useful information and support decision-making process.
During performing Data analysis we can identify patterns, trends, relationships, or insights.
Data analysis includes computational tools to clean and transform raw data, statistical methods and visualization techniques.
Data analysis has become essential in today’s world because organizations and individuals generate massive amounts of data every day.
By analyzing data, businesses and institutions can make informed management decisions, predict future outcomes, improve efficiency and reduce risks.
Application areas:

a) Business and Finance:
In business, data analysis helps companies understand customer preferences, optimize operation and increase profitability. Financial analysts use data to evaluate investments, forecast revenue
and assess risks. real-time analytics. Instead of analyzing data after it has been collected, companies now analyze data instantly as it is generated. This allows organizations to respond quickly
to changes.

b) Healthcare and Medicine:
In healthcare, data analysis is used to study patient data, track disease trends, and improve treatment
outcomes. Hospitals analyze medical records to identify effective treatments.The scientists are developing
vaccines and other drugs faster. During the COVID-19 pandemic, data analysis was used worldwide to track
infection rates and predict the spread of the virus.

c) Marketing and Advertising:
Data analysis helps companies understand consumer behavior and preferences. By analyzing customer data such as browsing history, purchases, and engagement with advertisements, businesses can create targeted
marketing campaigns.

Conclusion:
Including modern trends and real-world examples shows that data analysis is not only a theoretical concept but also a powerful tool used in many industries today.
As technology continues to advance, the role of data analysis will become even more important for decision-making and innovation.

Exercise 2: Dataset Loading and Initial Analysis

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.5)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

2.1. Time Americans Spend Sleeping.csv:

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Time Americans Spend Sleeping.csv to Time Americans Spend Sleeping.csv

In [ ]:
import pandas as pd

df = pd.read_csv("Time Americans Spend Sleeping.csv")
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB

In [ ]:
df.describe()

            index         Year  Avg hrs per day sleeping  Standard Error
count  945.000000   945.000000                945.000000      945.000000
mean   472.000000  2010.000000                  8.806868        0.086958
std    272.942302     4.322782                  0.545001        0.034631
min      0.000000  2003.000000                  7.720000        0.018000
25%    236.000000  2006.000000                  8.360000        0.063000
50%    472.000000  2010.000000                  8.810000        0.084000
75%    708.000000  2014.000000                  9.190000        0.106000
max    944.000000  2017.000000                 10.650000        0.228000

In [ ]:
df.shape

(945, 9)

In [ ]:
df.columns

Index(['index', 'Year', 'Period', 'Avg hrs per day sleeping', 'Standard Error',
       'Type of Days', 'Age Group', 'Activity', 'Sex'],
      dtype='object')

Dataset description: The dataset contains information about sleep habits and lifestyle factors affecting sleep health. It includes variables such as age, gender, occupation, sleep duration, stress level, and physical activity. The data can be used to analyze patterns in sleep behavior and understand how lifestyle factors influence sleep quality.

2.2. Mental health Depression disorder Data.csv:

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Mental health Depression disorder Data.csv to Mental health Depression disorder Data.csv

In [ ]:
import pandas as pd

df = pd.read_csv("Mental health Depression disorder Data.csv")
df.head()

/tmp/ipykernel_227/592763949.py:3: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Mental health Depression disorder Data.csv")

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [ ]:
df.describe()

,index,Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
count,108553.000000,6468.000000,6468.000000,6468.000000,6468.000000
mean,54276.000000,3.989921,0.862278,3.497654,1.585821
std,31336.696223,1.167526,0.460679,0.655859,0.860283
min,0.000000,2.023393,0.383650,2.139903,0.446940
25%,27138.000000,3.188824,0.535064,3.005529,0.993685
50%,54276.000000,3.554373,0.726430,3.499606,1.479936
75%,81414.000000,4.682163,0.940157,3.912381,1.867834
max,108552.000000,8.967330,3.452476,6.602754,5.474668

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108553 entries, 0 to 108552
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   index                      108553 non-null  int64
 1   Entity                     108553 non-null  object
 2   Code                       103141 non-null  object
 3   Year                       108553 non-null  object
 4   Schizophrenia (%)          25875 non-null   object
 5   Bipolar disorder (%)       19406 non-null   object
 6   Eating disorders (%)       100236 non-null  object
 7   Anxiety disorders (%)      6468 non-null    float64
 8   Drug use disorders (%)     6468 non-null    float64
 9   Depression (%)             6468 non-null    float64
 10  Alcohol use disorders (%)  6468 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 9.1+ MB

In [ ]:
df.shape

(108553, 11)

In [ ]:
df.columns

Index(['index', 'Entity', 'Code', 'Year', 'Schizophrenia (%)',
       'Bipolar disorder (%)', 'Eating disorders (%)', 'Anxiety disorders (%)',
       'Drug use disorders (%)', 'Depression (%)',
       'Alcohol use disorders (%)'],
      dtype='object')

Dataset description: The dataset presents global statistics on mental health disorders across different countries and years.
It includes data on the prevalence of disorders such as depression and anxiety.
The dataset can be used to analyze mental health trends worldwide.

2.3. Credit Card Approvals:

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving clean_dataset.csv to clean_dataset (1).csv

In [ ]:
import pandas as pd

df = pd.read_csv("clean_dataset.csv")
df.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [ ]:
df.describe()

,Gender,Age,Debt,Married,BankCustomer,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,ZipCode,Income,Approved
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000
mean,0.695652,31.514116,4.758725,0.760870,0.763768,2.223406,0.523188,0.427536,2.40000,0.457971,180.547826,1017.385507,0.444928
std,0.460464,11.860245,4.978163,0.426862,0.425074,3.346513,0.499824,0.495080,4.86294,0.498592,173.970323,5210.102598,0.497318
min,0.000000,13.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,22.670000,1.000000,1.000000,1.000000,0.165000,0.000000,0.000000,0.00000,0.000000,60.000000,0.000000,0.000000
50%,1.000000,28.460000,2.750000,1.000000,1.000000,1.000000,1.000000,0.000000,0.00000,0.000000,160.000000,5.000000,0.000000
75%,1.000000,37.707500,7.207500,1.000000,1.000000,2.625000,1.000000,1.000000,3.00000,1.000000,272.000000,395.500000,1.000000
max,1.000000,80.250000,28.000000,1.000000,1.000000,28.500000,1.000000,1.000000,67.00000,1.000000,2000.000000,100000.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    object
 6   Ethnicity       690 non-null    object
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    object
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    int64
dtypes: float64(3), int64(10), object(3)
memory usage: 86.4+ KB

In [ ]:
df.shape

(690, 16)

In [ ]:
df.columns

Index(['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'Industry',
       'Ethnicity', 'YearsEmployed', 'PriorDefault', 'Employed', 'CreditScore',
       'DriversLicense', 'Citizen', 'ZipCode', 'Income', 'Approved'],
      dtype='object')

Dataset description: This dataset contains financial and demographic information used to evaluate credit card applications.
It includes variables such as income, employment status, and credit history.
The dataset can be used to analyze factors affecting credit card approval decisions.

Exercise 4: Exploring Data Types

In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Time Americans Spend Sleeping.csv")

df.head()

Saving Time Americans Spend Sleeping.csv to Time Americans Spend Sleeping (5).csv

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [ ]:
df.columns

Index(['index', 'Year', 'Period', 'Avg hrs per day sleeping', 'Standard Error',
       'Type of Days', 'Age Group', 'Activity', 'Sex'],
      dtype='object')

**Time Americans Spend Sleeping:**
'index' - Quantitative/Discrete, 'Year' - Quantitative/Discrete, 'Period' - Qualitative/Ordinal, 'Avg hrs per day sleeping' - Quantitative/Continuous, 'Standard Error' - Quantitative/Continuous, 'Type of Days' - Qualitative/Nominal, 'Age Group' - Qualitative/Ordinal, 'Activity' - Qualitative/Nominal, 'Sex' - Qualitative/Nominal

In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Mental health Depression disorder Data.csv")

df.head()

Saving Mental health Depression disorder Data.csv to Mental health Depression disorder Data.csv

/tmp/ipykernel_413/2675301194.py:6: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Mental health Depression disorder Data.csv")

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [ ]:
df.columns

Index(['index', 'Entity', 'Code', 'Year', 'Schizophrenia (%)',
       'Bipolar disorder (%)', 'Eating disorders (%)', 'Anxiety disorders (%)',
       'Drug use disorders (%)', 'Depression (%)',
       'Alcohol use disorders (%)'],
      dtype='object')

**Mental Health Depression Disorder: **
'index'- Quantitative/Discrete, 'Entity' - Qualitative/Nominal, 'Code' - Qualitative/Nominal, 'Year' - Quantitative/Discrete, 'Schizophrenia (%) - Quantitative/Continuous', 'Bipolar disorder (%)' - Quantitative/Continuous, 'Eating disorders (%)' - Quantitative/Continuous, 'Anxiety disorders (%)' - Quantitative/Continuous, 'Drug use disorders (%)' - Quantitative/Continuous, 'Depression (%)'- Quantitative/Continuous, 'Alcohol use disorders (%) - Quantitative/Continuous'.

In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("clean_dataset.csv")

df.head()

Saving clean_dataset.csv to clean_dataset.csv

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [ ]:
df. columns

Index(['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'Industry',
       'Ethnicity', 'YearsEmployed', 'PriorDefault', 'Employed', 'CreditScore',
       'DriversLicense', 'Citizen', 'ZipCode', 'Income', 'Approved'],
      dtype='object')

**Credit Card Approvals: **
'Gender'- Qualitative/Nominal, 'Age' - Quantitative/Continuous, 'Debt' - Quantitative/Continuous, 'Married' - Qualitative/Nominal, 'BankCustomer' - Qualitative/Nominal, 'Industry' Qualitative/Nominal, 'Ethnicity' - Qualitative/Nominal, 'YearsEmployed' - Quantitative/Continuous, 'PriorDefault' - Qualitative/Nominal, 'Employed' - Qualitative/Nominal, 'CreditScore' - Quantitative/Discrete, 'DriversLicense' - Qualitative/Nominal, 'Citizen' - Qualitative/Nominal, 'ZipCode' - Qualitative/Nominal, 'Income' - Quantitative/Continuous, 'Approved' - Qualitative/Nominal.

Exercise 5: Basic Observation Skills in Data Analysis:

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("Time Americans Spend Sleeping.csv")
df.head()

Saving Time Americans Spend Sleeping.csv to Time Americans Spend Sleeping (1).csv

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [ ]:
df.columns

Index(['index', 'Year', 'Period', 'Avg hrs per day sleeping', 'Standard Error',
       'Type of Days', 'Age Group', 'Activity', 'Sex'],
      dtype='object')

1. Trend Analysis: "Year" and "Avg hrs per day sleeping"
These variables allow us to analyze how the average sleep duration of Americans has changed over time.
By plotting sleep duration against year, we can identify trends or long-term patterns in sleeping habits.

2. Group Comparison by Age: "Age Group" and "Avg hrs per day sleeping"
This comparison allows us to analyze whether different age groups sleep different amounts of time. It helps identify patterns such as whether younger or older individuals tend to sleep more.

3. Gender Comparison: "Sex and "Avg hrs per day sleeping".
These variables allow comparison of average sleep duration between males and females. This type of analysis can reveal gender-based differences in sleep patterns.

4. Weekday and Weekend comparison: "Type of Days" and "Avg hrs per day sleeping"
This analysis can show whether people sleep more on weekends compared to weekdays. It helps understand behavioral differences in sleep patterns depending on the day type.

Exercise 6: Identifying Data Types:

A company’s financial reports stored in an Excel file	- Structured data,

Photographs uploaded to a social media platform	- Unstructured data,

A collection of news articles on a website	- Unstructured data,

Inventory data in a relational database	- Structured data,

Recorded interviews from a market research study - Unstructured data.

Exercise 7: Transformation exercise:

**A series of blog posts about travel experiences:**	Text processing and Natural Language Processing (NLP) to extract key fields such as destination, travel date, transportation, budget and sentiment.

**Audio recordings of customer service calls:** Speech-to-text software to transcribe the audio, then apply text analysis to extract customer name, issue type, call duration, resolution status and sentiment.

**Handwritten notes from a brainstorming session:** Optical character recognition (OCR) or handwriting recognition to digitize the notes, then categorize the extracted text into themes, action items and responsible persons.

**Video tutorial on cooking:** Extract the audio and convert it to text using speech recognition, then identify structured fields such as recipe name, ingredients, quantities, cooking time and preparation steps.

Exercise 8: Import a file from Kaggle:

In [10]:
!wget "https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/train.zip"

--2026-03-14 18:15:35--  https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/train.zip
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/train.zip [following]
--2026-03-14 18:15:36--  https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/train.zip
Resolving media.githubusercontent.com (media.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22494 (22K) [application/zip]
Saving to: ‘train.zip.1’

train.zip.1         100%[===================>]  21.97K  --.-KB/s    in 0.001s

2026-03-14 18:15:36 (19.4 MB/s) - ‘train.zip.1’ saved [22494/22494]

In [7]:
import zipfile

with zipfile.ZipFile("train.zip", 'r') as zip_ref:
    zip_ref.extractall()

In [8]:
import pandas as pd

df = pd.read_csv("train.csv")

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Exercise 9 : Export a dataframe to excel format and JSON format:

In [21]:
import pandas as pd
from google.colab import files

# Dataset:
data = {
    "Customer": ["Anna", "Sergei", "Nina", "Petr"],
    "Product": ["Laptop", "Tablet", "Smartphone", "Laptop"],
    "Price": [1200, 900, 500, 1150],
    "Quantity": [1, 2, 1, 1],
    "Purchase_Date": ["2026-03-01", "2026-03-01", "2026-03-02", "2026-03-03"]
}

df = pd.DataFrame(data)

# Files:
df.to_excel("sales_data.xlsx")
df.to_json("sales_data.json")

# Download:
files.download("sales_data.xlsx")
files.download("sales_data.json")

Exercise 10: Reading JSON Data:

In [22]:
import pandas as pd
import zipfile

!wget "https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/posts.zip"

with zipfile.ZipFile("posts.zip", "r") as zip_ref:
    zip_ref.extractall()

df = pd.read_json("posts.json")

df.head()

--2026-03-14 18:53:07--  https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/posts.zip
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/posts.zip [following]
--2026-03-14 18:53:07--  https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/posts.zip
Resolving media.githubusercontent.com (media.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7245 (7.1K) [application/zip]
Saving to: ‘posts.zip’

posts.zip           100%[===================>]   7.08K  --.-KB/s    in 0s

2026-03-14 18:53:07 (78.3 MB/s) - ‘posts.zip’ saved [7245/7245]

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...